import math
import random

#Problem - Guess the number generated by the system

#1. Get the lower and upper value from user 
lower = int(input("Provide lower value: " ))
upper = int(input("Provide upper value: "))

#2. Generate Random number 
num = random.randint(lower,upper)

#3. Get the guess number the user 
guess = int(input("Input your guess: "))

#4. Make user guess the value 
while guess != num:
    if guess > num: 
        print("Guess is less than the value")
        guess = int(input("Input your guess: "))
    elif guess < num: 
        print("Guess is greater than the value")
        guess = int(input("Input your guess: "))   

print("You guess is correct!") 